[tool.flake8]
exclude = "Cutie"
ignore = "H,E501,W503,F841,F401"

[tool.isort] # not used for now
profile = "black"
line_length = 120

[tool.black]
line-length = 120
target-version = ["py38", "py39"]
exclude = "Cutie"

[tool.mypy]
python_version = 3.9
exclude = "Cutie"
show_error_codes = true
warn_unused_ignores = false
check_untyped_defs = true

[[tool.mypy.overrides]]
module = [
       "rospy",
       "rostest",
       "rospkg",
       "cv_bridge",
       "dynamic_reconfigure.*",
       "tracking_ros.cfg",
       "std_srvs.srv",
       "sensor_msgs.msg",
       "geometry_msgs.msg",
       "jsk_recognition_msgs.msg",
       "jsk_topic_tools",
       "jsk_data",
       "torchvision",
       "supervision",
       "omegaconf",
       "hydra",
       "deva.*",
       "cutie.*",
       "groundingdino.*",
       "GroundingDINO.*",
       "segment_anything",
       "segment_anything_hq",
       "mobile_sam"
]
ignore_missing_imports = true

